##################################################################################
#
# OWNER: Robert Andrew Brown & Joseph Rugh
# PROGRAMMER: Robert Andrew Brown & Joseph Rugh
# PROJECT: forgestorm-realms
# DATE: 7/4/2017
# _______________________________________________________________________________
#
# Copyright © 2017 ForgeStorm.com. All Rights Reserved.
#
# No part of this project and/or code and/or source code and/or source may be 
# reproduced, distributed, or transmitted in any form or by any means, 
# including photocopying, recording, or other electronic or mechanical methods, 
# without the prior written permission of the owner.
##